#!/usr/bin/env python3
"""Apply stable DNS fallback settings to generated sing-box JSON profiles.

Default behavior:
- Main / legacy profiles use legacy DNS format compatible with older clients:
  {"tag": "cloudflare", "address": "1.1.1.1"}
- Files whose name contains "new-dns" or already use DNS server `type` keep the new DNS format:
  {"type": "udp", "tag": "cloudflare", "server": "1.1.1.1"}
- Summary JSON files are skipped.

This script is intentionally post-processing only. It does not regenerate profiles,
so it is safe to run after OpenClash -> sing-box conversion, link merge, and
mobile idle stabilization.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Tuple


DEFAULT_PRIMARY_TAG = "cloudflare"
DEFAULT_PRIMARY_DNS = "1.1.1.1"
DEFAULT_FALLBACK_TAG = "google"
DEFAULT_FALLBACK_DNS = "8.8.8.8"
DEFAULT_REPORT = "summary_dns_fallback_stable.json"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path: Path, data: Any) -> None:
    path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def looks_like_singbox_config(data: Any) -> bool:
    if not isinstance(data, dict):
        return False
    # Real sing-box profiles generated by this project always have outbounds.
    return isinstance(data.get("outbounds"), list)


def is_summary_file(path: Path) -> bool:
    name = path.name.lower()
    return name.startswith("summary") or name.startswith("report")


def has_new_dns_format(data: Dict[str, Any]) -> bool:
    dns = data.get("dns")
    if not isinstance(dns, dict):
        return False
    servers = dns.get("servers")
    if not isinstance(servers, list):
        return False
    return any(isinstance(item, dict) and "type" in item for item in servers)


def choose_dns_format(path: Path, data: Dict[str, Any], mode: str) -> str:
    if mode in {"legacy", "new"}:
        return mode
    name = path.name.lower()
    if "new-dns" in name:
        return "new"
    if has_new_dns_format(data):
        return "new"
    return "legacy"


def build_dns_servers(fmt: str, primary_tag: str, primary_dns: str, fallback_tag: str, fallback_dns: str) -> List[Dict[str, Any]]:
    if fmt == "new":
        return [
            {
                "type": "udp",
                "tag": primary_tag,
                "server": primary_dns,
            },
            {
                "type": "udp",
                "tag": fallback_tag,
                "server": fallback_dns,
            },
        ]
    return [
        {
            "tag": primary_tag,
            "address": primary_dns,
        },
        {
            "tag": fallback_tag,
            "address": fallback_dns,
        },
    ]


def normalize_dns_rules(dns: Dict[str, Any], allowed_tags: set[str], default_tag: str) -> int:
    """Rewrite stale DNS rule server references to the default server tag.

    Some generated configs may keep DNS rules pointing to a removed resolver tag.
    This prevents invalid/stale references after we intentionally reduce resolvers
    to a stable primary + fallback pair.
    """
    changed = 0
    rules = dns.get("rules")
    if not isinstance(rules, list):
        return changed

    for rule in rules:
        if not isinstance(rule, dict):
            continue
        server = rule.get("server")
        if isinstance(server, str) and server and server not in allowed_tags:
            rule["server"] = default_tag
            changed += 1
    return changed


def apply_dns_fallback(
    path: Path,
    data: Dict[str, Any],
    mode: str,
    primary_tag: str,
    primary_dns: str,
    fallback_tag: str,
    fallback_dns: str,
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    fmt = choose_dns_format(path, data, mode)
    dns = data.get("dns")
    if not isinstance(dns, dict):
        dns = {}

    before_servers = dns.get("servers") if isinstance(dns.get("servers"), list) else []

    dns["servers"] = build_dns_servers(
        fmt=fmt,
        primary_tag=primary_tag,
        primary_dns=primary_dns,
        fallback_tag=fallback_tag,
        fallback_dns=fallback_dns,
    )
    dns["final"] = primary_tag

    # Keep existing strategy/cache fields if present. Only stale rule server refs are normalized.
    stale_rule_refs_fixed = normalize_dns_rules(
        dns=dns,
        allowed_tags={primary_tag, fallback_tag},
        default_tag=primary_tag,
    )

    data["dns"] = dns

    detail = {
        "file": str(path),
        "format": fmt,
        "primary": primary_dns,
        "fallback": fallback_dns,
        "final": primary_tag,
        "server_count_before": len(before_servers),
        "server_count_after": len(dns["servers"]),
        "stale_dns_rule_refs_fixed": stale_rule_refs_fixed,
    }
    return data, detail


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Apply stable DNS fallback to sing-box JSON profiles."
    )
    parser.add_argument("--dir", default="output/SingBox", help="Directory containing sing-box JSON files.")
    parser.add_argument("--mode", choices=["preserve", "legacy", "new"], default="preserve", help="DNS config format to write. preserve keeps main files legacy and new-dns files new.")
    parser.add_argument("--primary-tag", default=DEFAULT_PRIMARY_TAG)
    parser.add_argument("--primary", default=DEFAULT_PRIMARY_DNS)
    parser.add_argument("--fallback-tag", default=DEFAULT_FALLBACK_TAG)
    parser.add_argument("--fallback", default=DEFAULT_FALLBACK_DNS)
    parser.add_argument("--report", default=DEFAULT_REPORT)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    base = Path(args.dir)
    base.mkdir(parents=True, exist_ok=True)

    processed = []
    skipped = []
    errors = []

    for path in sorted(base.glob("*.json")):
        if is_summary_file(path):
            skipped.append({"file": str(path), "reason": "summary/report file"})
            continue

        try:
            data = load_json(path)
        except Exception as exc:
            errors.append({"file": str(path), "error": f"json load failed: {exc}"})
            continue

        if not looks_like_singbox_config(data):
            skipped.append({"file": str(path), "reason": "not a sing-box profile"})
            continue

        try:
            new_data, detail = apply_dns_fallback(
                path=path,
                data=data,
                mode=args.mode,
                primary_tag=args.primary_tag,
                primary_dns=args.primary,
                fallback_tag=args.fallback_tag,
                fallback_dns=args.fallback,
            )
            if not args.dry_run:
                save_json(path, new_data)
            processed.append(detail)
        except Exception as exc:
            errors.append({"file": str(path), "error": str(exc)})

    report = {
        "ok": not errors,
        "mode": args.mode,
        "primary_tag": args.primary_tag,
        "primary_dns": args.primary,
        "fallback_tag": args.fallback_tag,
        "fallback_dns": args.fallback,
        "processed_count": len(processed),
        "skipped_count": len(skipped),
        "error_count": len(errors),
        "processed": processed,
        "skipped": skipped,
        "errors": errors,
    }

    report_path = base / args.report
    if not args.dry_run:
        save_json(report_path, report)

    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if not errors else 1


if __name__ == "__main__":
    raise SystemExit(main())
