#!/usr/bin/env python3
"""Build stable sing-box profiles from existing test reports.

This script does not test proxies. It consumes committed reports generated by the
main workflow and creates:
- output/SingBox/best-stable.json
- output/SingBox/mobile-stable.json
- output/SingBox/fallback-stable.json
- output/SingBox/manual-links.json
- output/Health/healthy.csv
- output/Health/quarantine.csv
- output/Health/summary_health.json
- output/SingBox/summary_best_stable.json

Manual nodes from input/links.txt are treated as trusted. They are not marked as
failed only because they do not appear in Alive/BestPing reports.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import shutil
from copy import deepcopy
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

AUTO_TAG = "AUTO-BEST-STABLE"
PROXY_TAG = "PROXY"
DIRECT_TAG = "DIRECT"
MANUAL_PREFIX_DEFAULT = "LINK"
TEST_URL_DEFAULT = "https://www.gstatic.com/generate_204"
REGULAR_OUTBOUND_TYPES = {
    "vmess",
    "vless",
    "trojan",
    "shadowsocks",
    "hysteria",
    "hysteria2",
    "tuic",
    "wireguard",
    "ssh",
    "socks",
    "http",
}
GROUP_OUTBOUND_TYPES = {"selector", "urltest"}
SPECIAL_TYPES = {"direct", "block", "dns"}


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def iso(dt: Optional[datetime] = None) -> str:
    return (dt or utc_now()).isoformat(timespec="seconds")


def parse_iso(text: str | None) -> Optional[datetime]:
    if not text:
        return None
    try:
        return datetime.fromisoformat(str(text).replace("Z", "+00:00"))
    except Exception:
        return None


def read_json(path: Path, default: Any = None) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return deepcopy(default)


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def parse_delay_ms(value: Any) -> Optional[int]:
    if value is None:
        return None
    text = str(value).strip().lower()
    if not text:
        return None
    match = re.search(r"\d+", text)
    if not match:
        return None
    try:
        return int(match.group(0))
    except Exception:
        return None


def read_csv_rows(path: Path) -> List[dict]:
    if not path.exists():
        return []
    try:
        with path.open("r", encoding="utf-8", errors="replace", newline="") as fh:
            return list(csv.DictReader(fh))
    except Exception:
        return []


def normalize_name(value: Any) -> str:
    return str(value or "").strip()


def collect_measurements(root: Path) -> Dict[str, Dict[str, Any]]:
    """Collect measurements by tag/name from BestPing/Alive CSV files."""
    candidates = [
        (root / "output/BestPing/top5_indonesia_ping.csv", True),
        (root / "output/BestPing/top5_best_ping.csv", True),
        (root / "output/Alive/alive.csv", False),
        (root / "output/Alive/check_result.csv", False),
    ]
    by_name: Dict[str, Dict[str, Any]] = {}

    for path, prefiltered in candidates:
        rows = read_csv_rows(path)
        for row in rows:
            name = normalize_name(row.get("name"))
            if not name:
                continue
            delay = parse_delay_ms(row.get("delay_ms") or row.get("delay") or row.get("latency"))
            raw_status = str(row.get("status", "")).strip().lower()
            status = "alive" if prefiltered and delay is not None else raw_status
            protocol = str(row.get("protocol", "")).strip()
            country = str(row.get("country", "")).strip()
            server = str(row.get("server", "")).strip()
            port = str(row.get("port", "")).strip()
            reason = str(row.get("reason", "")).strip()

            item = by_name.setdefault(
                name,
                {
                    "name": name,
                    "delays": [],
                    "success_count": 0,
                    "fail_count": 0,
                    "sources": [],
                    "protocol": protocol,
                    "country": country,
                    "server": server,
                    "port": port,
                    "reason": reason,
                },
            )
            if protocol and not item.get("protocol"):
                item["protocol"] = protocol
            if country and not item.get("country"):
                item["country"] = country
            if server and not item.get("server"):
                item["server"] = server
            if port and not item.get("port"):
                item["port"] = port
            if reason:
                item["reason"] = reason
            item["sources"].append(str(path))

            if status == "alive" and delay is not None:
                item["success_count"] += 1
                item["delays"].append(delay)
            elif status and status not in {"alive", "ok", "success"}:
                item["fail_count"] += 1
            elif delay is None and not prefiltered and raw_status:
                item["fail_count"] += 1

    for item in by_name.values():
        delays = item.get("delays") or []
        item["best_delay_ms"] = min(delays) if delays else None
        item["avg_delay_ms"] = round(sum(delays) / len(delays), 2) if delays else None
        item["jitter_ms"] = (max(delays) - min(delays)) if len(delays) >= 2 else 0
        total = int(item.get("success_count", 0)) + int(item.get("fail_count", 0))
        item["success_rate"] = round(item.get("success_count", 0) / total, 4) if total else None
    return by_name


def regular_outbounds(config: dict) -> List[dict]:
    return [
        item
        for item in config.get("outbounds", [])
        if isinstance(item, dict)
        and item.get("tag")
        and str(item.get("type", "")).lower() in REGULAR_OUTBOUND_TYPES
    ]


def is_manual_tag(tag: str, manual_prefix: str) -> bool:
    return str(tag or "").strip().upper().startswith(manual_prefix.upper())


def score_node(measurement: dict, state_item: dict, delay_penalty_weight: float = 0.35) -> float:
    delay = measurement.get("best_delay_ms")
    avg = measurement.get("avg_delay_ms") or delay or 999999
    jitter = measurement.get("jitter_ms") or 0
    success_rate = measurement.get("success_rate")
    if success_rate is None:
        success_rate = 1.0 if delay is not None else 0.0
    fail_streak = int(state_item.get("fail_streak", 0) or 0)
    success_streak = int(state_item.get("success_streak", 0) or 0)
    return float(avg) + (float(jitter) * delay_penalty_weight) + ((1.0 - float(success_rate)) * 2500.0) + (fail_streak * 600.0) - min(success_streak * 15.0, 150.0)


def update_health_state(
    state: dict,
    measurements: Dict[str, dict],
    outbound_tags: Iterable[str],
    manual_prefix: str,
    max_delay_ms: int,
    quarantine_after_failures: int,
    quarantine_hours: int,
) -> dict:
    now = utc_now()
    nodes = state.setdefault("nodes", {})
    tags_set = set(outbound_tags)

    for tag in tags_set:
        item = nodes.setdefault(tag, {"name": tag})
        item["name"] = tag
        item.setdefault("fail_streak", 0)
        item.setdefault("success_streak", 0)
        item.setdefault("quarantine_count", 0)

        if is_manual_tag(tag, manual_prefix) and tag not in measurements:
            item["trusted_manual"] = True
            item["last_status"] = "trusted_manual"
            item["last_seen_at"] = iso(now)
            item["quarantined_until"] = ""
            continue

        measurement = measurements.get(tag)
        if not measurement:
            # Do not punish unmeasured nodes: some files may not be part of current test scope.
            item["last_status"] = item.get("last_status", "unknown")
            continue

        delay = measurement.get("best_delay_ms")
        ok = bool(measurement.get("success_count", 0) > 0 and delay is not None and int(delay) <= int(max_delay_ms))
        item["last_seen_at"] = iso(now)
        item["last_delay_ms"] = delay
        item["avg_delay_ms"] = measurement.get("avg_delay_ms")
        item["jitter_ms"] = measurement.get("jitter_ms")
        item["success_rate"] = measurement.get("success_rate")
        item["protocol"] = measurement.get("protocol", item.get("protocol", ""))
        item["country"] = measurement.get("country", item.get("country", ""))
        item["server"] = measurement.get("server", item.get("server", ""))
        item["port"] = measurement.get("port", item.get("port", ""))
        item["trusted_manual"] = is_manual_tag(tag, manual_prefix)

        if ok:
            item["success_streak"] = int(item.get("success_streak", 0) or 0) + 1
            item["fail_streak"] = 0
            item["last_status"] = "healthy"
            item["quarantined_until"] = ""
        else:
            item["success_streak"] = 0
            item["fail_streak"] = int(item.get("fail_streak", 0) or 0) + 1
            item["last_status"] = "failed" if delay is None else "slow"
            if int(item["fail_streak"]) >= int(quarantine_after_failures):
                until = now + timedelta(hours=int(quarantine_hours))
                item["quarantined_until"] = iso(until)
                item["quarantine_count"] = int(item.get("quarantine_count", 0) or 0) + 1
                item["last_status"] = "quarantined"

    # Expire old quarantine windows.
    for item in nodes.values():
        until = parse_iso(item.get("quarantined_until"))
        if until and until <= now:
            item["quarantined_until"] = ""
            if item.get("last_status") == "quarantined":
                item["last_status"] = "expired_quarantine"

    state["updated_at"] = iso(now)
    state["manual_prefix"] = manual_prefix
    state["max_delay_ms"] = max_delay_ms
    state["quarantine_after_failures"] = quarantine_after_failures
    state["quarantine_hours"] = quarantine_hours
    return state


def is_quarantined(item: dict) -> bool:
    until = parse_iso(item.get("quarantined_until"))
    return bool(until and until > utc_now())


def choose_nodes(
    base_outbounds: List[dict],
    measurements: Dict[str, dict],
    state: dict,
    manual_prefix: str,
    stable_max_delay_ms: int,
    max_stable: int,
    max_fallback: int,
    max_manual: int,
) -> Tuple[List[str], List[str], List[str], List[dict], List[dict]]:
    nodes = state.get("nodes", {})
    tag_to_out = {str(item.get("tag")): item for item in base_outbounds if item.get("tag")}

    scored: List[Tuple[float, str, dict]] = []
    healthy_rows: List[dict] = []
    quarantine_rows: List[dict] = []
    manual_tags: List[str] = []

    for tag in tag_to_out:
        state_item = nodes.get(tag, {})
        measurement = measurements.get(tag, {})
        manual = is_manual_tag(tag, manual_prefix)
        if manual:
            manual_tags.append(tag)

        row = {
            "name": tag,
            "protocol": measurement.get("protocol") or state_item.get("protocol") or tag_to_out[tag].get("type", ""),
            "country": measurement.get("country") or state_item.get("country", ""),
            "server": measurement.get("server") or state_item.get("server", ""),
            "port": measurement.get("port") or state_item.get("port", ""),
            "delay_ms": measurement.get("best_delay_ms") or state_item.get("last_delay_ms"),
            "avg_delay_ms": measurement.get("avg_delay_ms") or state_item.get("avg_delay_ms"),
            "jitter_ms": measurement.get("jitter_ms") or state_item.get("jitter_ms"),
            "success_rate": measurement.get("success_rate") or state_item.get("success_rate"),
            "success_streak": state_item.get("success_streak", 0),
            "fail_streak": state_item.get("fail_streak", 0),
            "status": state_item.get("last_status", "unknown"),
            "quarantined_until": state_item.get("quarantined_until", ""),
            "trusted_manual": str(bool(manual)).lower(),
        }

        if is_quarantined(state_item):
            quarantine_rows.append(row)
            continue

        delay = parse_delay_ms(row.get("delay_ms"))
        if measurement and delay is not None and delay <= stable_max_delay_ms:
            score = score_node(measurement, state_item)
            row["score"] = round(score, 2)
            scored.append((score, tag, row))
            healthy_rows.append(row)
        elif manual and not measurement:
            # Trusted manual links are not tested by request. Keep them as fallback candidates.
            row["score"] = 5000
            healthy_rows.append(row)

    scored.sort(key=lambda item: (item[0], item[1].lower()))
    stable_tags = [tag for _, tag, _ in scored[:max_stable]]

    # Add a few trusted manual tags at the end so manually supplied known-good links stay available.
    for tag in manual_tags:
        if tag not in stable_tags and not is_quarantined(nodes.get(tag, {})) and len(stable_tags) < max_stable:
            stable_tags.append(tag)
            if len([t for t in stable_tags if is_manual_tag(t, manual_prefix)]) >= max_manual:
                break

    fallback_tags = [tag for _, tag, _ in scored[:max_fallback]]
    for tag in manual_tags:
        if tag not in fallback_tags and not is_quarantined(nodes.get(tag, {})) and len(fallback_tags) < max_fallback:
            fallback_tags.append(tag)

    if not stable_tags:
        # Last-resort fallback: keep first non-quarantined regular outbound so profile is not empty.
        for tag in tag_to_out:
            if not is_quarantined(nodes.get(tag, {})):
                stable_tags.append(tag)
                break
    if not fallback_tags:
        fallback_tags = stable_tags[:]

    manual_only = [tag for tag in manual_tags if not is_quarantined(nodes.get(tag, {}))]
    return stable_tags, fallback_tags, manual_only, healthy_rows, quarantine_rows


def make_direct_outbound() -> dict:
    return {"type": "direct", "tag": DIRECT_TAG}


def clone_selected_regular(base_regular: List[dict], selected_tags: List[str], connect_timeout: str) -> List[dict]:
    tag_set = set(selected_tags)
    result = []
    for item in base_regular:
        tag = str(item.get("tag"))
        if tag not in tag_set:
            continue
        cloned = deepcopy(item)
        cloned["connect_timeout"] = connect_timeout
        cloned.pop("tcp_fast_open", None)
        result.append(cloned)
    return result


def base_meta_config(config: dict) -> dict:
    keep_keys = ["log", "dns", "inbounds", "experimental"]
    result = {key: deepcopy(config[key]) for key in keep_keys if key in config}
    return result


def clean_route(route: dict, valid_tags: set[str], final_tag: str) -> dict:
    result = deepcopy(route or {})
    rules = result.get("rules")
    if isinstance(rules, list):
        for rule in rules:
            if not isinstance(rule, dict):
                continue
            if rule.get("outbound") and rule.get("outbound") not in valid_tags:
                rule["outbound"] = final_tag
            if rule.get("action") == "route" and rule.get("outbound") and rule.get("outbound") not in valid_tags:
                rule["outbound"] = final_tag
    result["final"] = final_tag
    return result


def build_profile(
    source_config: dict,
    base_regular: List[dict],
    selected_tags: List[str],
    profile_tag: str,
    test_url: str,
    interval: str,
    tolerance: int,
    idle_timeout: str,
    connect_timeout: str,
    interrupt: bool,
) -> dict:
    selected_tags = list(dict.fromkeys([tag for tag in selected_tags if tag]))
    result = base_meta_config(source_config)
    outbounds = [make_direct_outbound()]
    outbounds.extend(clone_selected_regular(base_regular, selected_tags, connect_timeout))

    if selected_tags:
        outbounds.append(
            {
                "type": "urltest",
                "tag": profile_tag,
                "outbounds": selected_tags,
                "url": test_url,
                "interval": interval,
                "tolerance": int(tolerance),
                "idle_timeout": idle_timeout,
                "interrupt_exist_connections": bool(interrupt),
            }
        )
        outbounds.append(
            {
                "type": "selector",
                "tag": PROXY_TAG,
                "outbounds": [profile_tag, DIRECT_TAG] + selected_tags,
                "default": profile_tag,
                "interrupt_exist_connections": False,
            }
        )
        final_tag = PROXY_TAG
    else:
        final_tag = DIRECT_TAG

    result["outbounds"] = outbounds
    valid_tags = {str(item.get("tag")) for item in outbounds if item.get("tag")}
    result["route"] = clean_route(source_config.get("route", {}), valid_tags, final_tag)
    return result


def write_csv(path: Path, rows: List[dict], fields: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fields})


def copy_if_exists(src: Path, dst: Path) -> None:
    if src.exists():
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default="output/SingBox/lengkap.json")
    parser.add_argument("--singbox-dir", default="output/SingBox")
    parser.add_argument("--health-dir", default="output/Health")
    parser.add_argument("--manual-prefix", default=MANUAL_PREFIX_DEFAULT)
    parser.add_argument("--stable-max-delay-ms", type=int, default=1800)
    parser.add_argument("--quarantine-after-failures", type=int, default=3)
    parser.add_argument("--quarantine-hours", type=int, default=24)
    parser.add_argument("--max-stable", type=int, default=10)
    parser.add_argument("--max-fallback", type=int, default=15)
    parser.add_argument("--max-manual", type=int, default=4)
    parser.add_argument("--test-url", default=TEST_URL_DEFAULT)
    parser.add_argument("--interval", default="3m")
    parser.add_argument("--tolerance", type=int, default=80)
    parser.add_argument("--idle-timeout", default="2h")
    parser.add_argument("--connect-timeout", default="15s")
    parser.add_argument("--interrupt", action="store_true")
    parser.add_argument("--make-latest-stable", action="store_true")
    args = parser.parse_args()

    root = Path(".")
    source_path = Path(args.source)
    singbox_dir = Path(args.singbox_dir)
    health_dir = Path(args.health_dir)
    state_path = health_dir / "health_state.json"

    source_config = read_json(source_path, {})
    if not isinstance(source_config, dict) or not source_config.get("outbounds"):
        raise SystemExit(f"Source sing-box profile not found or invalid: {source_path}")

    base_regular = regular_outbounds(source_config)
    if not base_regular:
        raise SystemExit(f"No regular outbounds found in {source_path}")

    measurements = collect_measurements(root)
    state = read_json(state_path, {"nodes": {}})
    if not isinstance(state, dict):
        state = {"nodes": {}}

    all_tags = [str(item.get("tag")) for item in base_regular if item.get("tag")]
    state = update_health_state(
        state=state,
        measurements=measurements,
        outbound_tags=all_tags,
        manual_prefix=args.manual_prefix,
        max_delay_ms=args.stable_max_delay_ms,
        quarantine_after_failures=args.quarantine_after_failures,
        quarantine_hours=args.quarantine_hours,
    )

    stable_tags, fallback_tags, manual_tags, healthy_rows, quarantine_rows = choose_nodes(
        base_outbounds=base_regular,
        measurements=measurements,
        state=state,
        manual_prefix=args.manual_prefix,
        stable_max_delay_ms=args.stable_max_delay_ms,
        max_stable=args.max_stable,
        max_fallback=args.max_fallback,
        max_manual=args.max_manual,
    )

    singbox_dir.mkdir(parents=True, exist_ok=True)
    health_dir.mkdir(parents=True, exist_ok=True)

    stable_config = build_profile(
        source_config, base_regular, stable_tags, AUTO_TAG,
        args.test_url, args.interval, args.tolerance, args.idle_timeout,
        args.connect_timeout, args.interrupt,
    )
    mobile_config = build_profile(
        source_config, base_regular, stable_tags, "AUTO-MOBILE-STABLE",
        args.test_url, "3m", 100, "2h", "15s", False,
    )
    fallback_config = build_profile(
        source_config, base_regular, fallback_tags, "AUTO-FALLBACK-STABLE",
        args.test_url, "3m", 100, "3h", "15s", False,
    )
    manual_config = build_profile(
        source_config, base_regular, manual_tags, "AUTO-MANUAL-LINKS",
        args.test_url, "3m", 100, "3h", "15s", False,
    )

    write_json(singbox_dir / "best-stable.json", stable_config)
    write_json(singbox_dir / "mobile-stable.json", mobile_config)
    write_json(singbox_dir / "fallback-stable.json", fallback_config)
    if manual_tags:
        write_json(singbox_dir / "manual-links.json", manual_config)

    if args.make_latest_stable:
        copy_if_exists(singbox_dir / "best-stable.json", singbox_dir / "latest.json")

    fields = [
        "name", "protocol", "country", "server", "port", "delay_ms", "avg_delay_ms",
        "jitter_ms", "success_rate", "success_streak", "fail_streak", "status",
        "quarantined_until", "trusted_manual", "score",
    ]
    healthy_rows_sorted = sorted(
        healthy_rows,
        key=lambda row: (float(row.get("score") or 999999), str(row.get("name", "")).lower()),
    )
    quarantine_rows_sorted = sorted(quarantine_rows, key=lambda row: str(row.get("name", "")).lower())
    write_csv(health_dir / "healthy.csv", healthy_rows_sorted, fields)
    write_csv(health_dir / "quarantine.csv", quarantine_rows_sorted, fields)
    write_json(state_path, state)

    summary = {
        "ok": bool(stable_tags),
        "updated_at": iso(),
        "source": str(source_path),
        "regular_outbound_count": len(base_regular),
        "measurement_count": len(measurements),
        "healthy_count": len(healthy_rows_sorted),
        "quarantine_count": len(quarantine_rows_sorted),
        "stable_count": len(stable_tags),
        "fallback_count": len(fallback_tags),
        "manual_count": len(manual_tags),
        "stable_tags": stable_tags,
        "fallback_tags": fallback_tags,
        "manual_tags": manual_tags,
        "outputs": {
            "best_stable": str(singbox_dir / "best-stable.json"),
            "mobile_stable": str(singbox_dir / "mobile-stable.json"),
            "fallback_stable": str(singbox_dir / "fallback-stable.json"),
            "manual_links": str(singbox_dir / "manual-links.json") if manual_tags else "",
            "latest": str(singbox_dir / "latest.json") if args.make_latest_stable else "unchanged",
        },
        "policy": {
            "stable_max_delay_ms": args.stable_max_delay_ms,
            "quarantine_after_failures": args.quarantine_after_failures,
            "quarantine_hours": args.quarantine_hours,
            "manual_prefix": args.manual_prefix,
            "manual_links_are_trusted": True,
        },
    }
    write_json(health_dir / "summary_health.json", summary)
    write_json(singbox_dir / "summary_best_stable.json", summary)
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
